spring.application.name=AutoStack

server.port=8081
#by default every starting path
server.servlet.context-path=/api/v1
logging.level.org.springframework.security=DEBUG
spring.security.user.name=user
#spring.security.user.password=12345
#logging.level.org.springframework.security=TRACE